
unbind C-b # removes default ctrl+b prefix
set-option -g prefix C-a  # set leader key to ctrl-a

bind-key r source-file $HOME/.tmux.conf  # bind reload to ctrl+z then r

bind-key h split-window -h  # ctrl+z then h for horizontal split
bind-key v split-window -v  # ctrl+z then v for vertical split
bind q kill-pane  # kill the current pane

bind-key h select-pane -L  # 
bind-key j select-pane -D  # 
bind-key k select-pane -U  # 
bind-key l select-pane -R  # 

set -g mouse on  # allow resizing panes with the mouse
