# # https://github.com/tmux-plugins/tmux-pain-control/blob/master/pain_control.tmux
# -n = bind directly, without leader. Press the key globally.
# -g = Append key to key tables (used for key tables / chains). Rarely needed for normal splits or pane navigation.

# show installed plugins
# ~/.tmux/plugins/tpm/bin/install_plugins | cat

unbind C-b # removes default ctrl+b prefix
set-option -g prefix C-a  # set leader key to ctrl-a

# bind reload to ctrl+z then r
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded!"

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# bind q kill-pane  # kill the current pane

# bind -n C-H previous-window
# bind -n C-L next-window

bind-key -n C-Left  split-window -h # ctrl+left for horizontal split
bind-key -n C-Down  split-window -v # ctrl+down for vertical split

# # Kill current pane with Ctrl+Q
# bind-key -n C-q kill-pane

set -g mouse on  # allow resizing panes with the mouse

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Upgrade $TERM
set -g default-terminal "screen-256color"

# set the text navigation shortcuts to emacs style instead of vim style
# even if you use Vim normally, the tmux command prompt is single-line text input, and emacs-style navigation is usually faster for small edits than switching into vi mode.
set -g status-keys emacs

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'christoomey/vim-tmux-navigator'


# Initialize TPM (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

