
# because key bindings
unbind-key -T root -a # unbind the root table of keys, return to default map
unbind-key -T prefix -a # unbind the prefix table of keys

unbind C-b # removes default ctrl+b prefix
set-option -g prefix C-a  # set leader key to ctrl-a

bind-key x kill-pane  # ctrl+a then x to kill pane with no prompt

bind C-p previous-window  # easier and faster switching between next/prev window
bind C-n next-window  # easier and faster switching between next/prev window

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded!"  # bind reload to ctrl+z then r
set -g history-limit 50000 # increase scrollback buffer size from 2000 to 50000 lines
set -g mouse on  # allow resizing panes with the mouse
set -g display-time 4000  # increase tmux messages display duration from 750ms to 4s
set -g default-terminal "screen-256color"  # upgrade $TERM
set -g status-keys emacs  # in the command menu, set the text navigation shortcuts to emacs style instead of vim style, even if you use Vim normally, the tmux command prompt is single-line text input, and emacs-style navigation is usually faster for small edits than switching into vi mode.

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @plugin 'tmux-plugins/tmux-pain-control'
# leader + | to horizontal split
# leader + - (minus) to horiozntal split

set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'  # initialize TPM (keep this line at the very bottom of tmux.conf)

# # https://github.com/tmux-plugins/tmux-pain-control/blob/master/pain_control.tmux
# -n = bind directly, without leader. Press the key globally.
# -g = Append key to key tables (used for key tables / chains). Rarely needed for normal splits or pane navigation.
# https://github.com/tmux-plugins/tmux-sensible?tab=readme-ov-file

# show installed plugins
# ~/.tmux/plugins/tpm/bin/install_plugins | cat

# tmux list-keys (list all keys mapped in tmux)
