[default]
# Allow negotiation up to SMB 3.1.1
protocol_vers_map=6

# Disable packet signing to prevent kernel hangs
signing_required=no

# Disable Time Machine entitlement polling
ntfs_extent_cnt=0

# Disable buggy Multi-channel support
# Fix for Time Machine error in smbfs logs 
mc_on=no

# Disable folder notifications
notify_off=yes

# Disable directory caching
dir_cache_off=yes
dir_cache_max_cnt=0
dir_cache_max=0