#!python3
import os, sys
from pathlib import Path
from pathlib import WindowsPath

assert sys.argv[1]
folder = Path(sys.argv[1])

HOST_USER = "g1"
HOST_IP = "192.168.1.3"
HOST_PASS = "."

# NOTE: all destinations are relative to Home folder
# NOTE: destination does not need the name of the source, only parent.
dest = "Desktop"

cmd = f'sshpass -p "{HOST_PASS}" rsync -vvv -r --progress {folder} -a {HOST_USER}@{HOST_IP}:{dest}'

os.system(cmd)
    

